version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest # Usamos 2019 porque es una versión estable y compatible con SQL Server Standard
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Password" # ¡Cambia esta contraseña por una segura!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql # Persistencia de datos de SQL Server
    networks:
      - app_network

  wildfly:
    build:
      context: . # Busca el Dockerfile en el directorio actual
      dockerfile: Dockerfile_Wildfly
    container_name: wildfly
    ports:
      - "8080:8080" # Puerto HTTP para las aplicaciones
      - "9990:9990" # Puerto de administración de WildFly
    volumes:
      - wildfly_deployments:/opt/jboss/wildfly/standalone/deployments # Persistencia de deployments
      - wildfly_configuration:/opt/jboss/wildfly/standalone/configuration # Persistencia de configuración
    depends_on:
      - sqlserver # WildFly depende de que SQL Server esté corriendo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data:
  wildfly_deployments:
  wildfly_configuration: